import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Sidebar from '../global/sidebar';
import { api } from '../../../services/api';

const ReportSettingsPage: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  // Header settings
  const [headerEnabled, setHeaderEnabled] = useState(true);
  const [headerLayoutType, setHeaderLayoutType] = useState('three_column');
  const [leftLogoEnabled, setLeftLogoEnabled] = useState(true);
  const [rightLogoEnabled, setRightLogoEnabled] = useState(true);
  const [leftLogoFile, setLeftLogoFile] = useState<File | null>(null);
  const [rightLogoFile, setRightLogoFile] = useState<File | null>(null);
  const [leftLogoPreview, setLeftLogoPreview] = useState<string>('');
  const [rightLogoPreview, setRightLogoPreview] = useState<string>('');

  // Header text
  const [headerLine1, setHeaderLine1] = useState('Republic of the Philippines');
  const [headerLine2, setHeaderLine2] = useState('CEBU TECHNOLOGICAL UNIVERSITY');
  const [headerLine2Color, setHeaderLine2Color] = useState('#DC143C');
  const [headerLine2Bold, setHeaderLine2Bold] = useState(true);
  const [headerLine3, setHeaderLine3] = useState('M. J. Cuenco Avenue Cor. R. Palma Street, Cebu City, Philippines');
  const [headerLine4, setHeaderLine4] = useState('Website: http://www.ctu.edu.ph');
  const [headerLine5, setHeaderLine5] = useState('Phone: +6332 402 4060 loc. 1146');
  const [headerLine6, setHeaderLine6] = useState('UNIVERSITY ALUMNI AFFAIRS OFFICE');
  const [headerLine6Color, setHeaderLine6Color] = useState('#DC143C');
  const [headerLine6Bold, setHeaderLine6Bold] = useState(true);

  // Footer settings
  const [footerEnabled, setFooterEnabled] = useState(true);
  const [footerImageEnabled, setFooterImageEnabled] = useState(true);
  const [footerImageFile, setFooterImageFile] = useState<File | null>(null);
  const [footerImagePreview, setFooterImagePreview] = useState<string>('');
  const [footerText1, setFooterText1] = useState('Generated by Cebu Technological University Alumni Affairs Office');
  const [footerText2, setFooterText2] = useState('This report is generated automatically by the Alumni Tracking System');

  // Signature settings
  const [signatureEnabled, setSignatureEnabled] = useState(true);
  const [preparedByName, setPreparedByName] = useState('MARIE JOY B. ALIT, Ph.D.');
  const [preparedByTitle, setPreparedByTitle] = useState('University Director for Alumni Affairs');
  const [approvedByName, setApprovedByName] = useState('ROMEO P. MONTECILLO, Ph.D.');
  const [approvedByTitle, setApprovedByTitle] = useState('Vice President for Student Affairs');

  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      setLoading(true);
      const response = await api.get('shared/report-settings/');

      if (response.data.success && response.data.settings) {
        const s = response.data.settings;
        setHeaderEnabled(s.header_enabled ?? true);
        setHeaderLayoutType(s.header_layout_type ?? 'three_column');
        setLeftLogoEnabled(s.left_logo_enabled ?? true);
        setRightLogoEnabled(s.right_logo_enabled ?? true);
        setLeftLogoPreview(s.left_logo_url || '');
        setRightLogoPreview(s.right_logo_url || '');

        setHeaderLine1(s.header_line1 || '');
        setHeaderLine2(s.header_line2 || '');
        setHeaderLine2Color(s.header_line2_color || '#DC143C');
        setHeaderLine2Bold(s.header_line2_bold ?? true);
        setHeaderLine3(s.header_line3 || '');
        setHeaderLine4(s.header_line4 || '');
        setHeaderLine5(s.header_line5 || '');
        setHeaderLine6(s.header_line6 || '');
        setHeaderLine6Color(s.header_line6_color || '#DC143C');
        setHeaderLine6Bold(s.header_line6_bold ?? true);

        setFooterEnabled(s.footer_enabled ?? true);
        setFooterImageEnabled(s.footer_image_enabled ?? true);
        setFooterImagePreview(s.footer_image_url || '');

        setFooterText1(s.footer_text1 || '');
        setFooterText2(s.footer_text2 || '');

        setSignatureEnabled(s.signature_enabled ?? true);
        setPreparedByName(s.prepared_by_name || '');
        setPreparedByTitle(s.prepared_by_title || '');
        setApprovedByName(s.approved_by_name || '');
        setApprovedByTitle(s.approved_by_title || '');
      }
    } catch (error) {
      console.error('Error loading settings:', error);
      // Don't show error, just use defaults
    } finally {
      setLoading(false);
    }
  };

  const handleLogoUpload = (file: File | null, type: 'left' | 'right' | 'footer') => {
    if (!file) return;

    const reader = new FileReader();
    reader.onloadend = () => {
      const result = reader.result as string;
      if (type === 'left') {
        setLeftLogoFile(file);
        setLeftLogoPreview(result);
      } else if (type === 'right') {
        setRightLogoFile(file);
        setRightLogoPreview(result);
      } else if (type === 'footer') {
        setFooterImageFile(file);
        setFooterImagePreview(result);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleSave = async () => {
    try {
      setSaving(true);
      setSuccessMessage('');
      setErrorMessage('');

      const formData = new FormData();

      formData.append('header_enabled', String(headerEnabled));
      formData.append('header_layout_type', headerLayoutType);
      formData.append('left_logo_enabled', String(leftLogoEnabled));
      formData.append('right_logo_enabled', String(rightLogoEnabled));
      
      formData.append('header_line1', headerLine1);
      formData.append('header_line2', headerLine2);
      formData.append('header_line2_color', headerLine2Color);
      formData.append('header_line2_bold', String(headerLine2Bold));
      formData.append('header_line3', headerLine3);
      formData.append('header_line4', headerLine4);
      formData.append('header_line5', headerLine5);
      formData.append('header_line6', headerLine6);
      formData.append('header_line6_color', headerLine6Color);
      formData.append('header_line6_bold', String(headerLine6Bold));
      
      formData.append('footer_enabled', String(footerEnabled));
      formData.append('footer_image_enabled', String(footerImageEnabled));
      formData.append('footer_text1', footerText1);
      formData.append('footer_text2', footerText2);

      formData.append('signature_enabled', String(signatureEnabled));
      formData.append('prepared_by_name', preparedByName);
      formData.append('prepared_by_title', preparedByTitle);
      formData.append('approved_by_name', approvedByName);
      formData.append('approved_by_title', approvedByTitle);

      if (leftLogoFile) {
        formData.append('left_logo', leftLogoFile);
      }
      if (rightLogoFile) {
        formData.append('right_logo', rightLogoFile);
      }
      if (footerImageFile) {
        formData.append('footer_image', footerImageFile);
      }

      const response = await api.post(
        'shared/report-settings/update/',
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data'
          }
        }
      );

      if (response.data.success) {
        setSuccessMessage('Report settings saved successfully!');
        setTimeout(() => setSuccessMessage(''), 3000);
      }
    } catch (error: any) {
      console.error('Error saving settings:', error);
      setErrorMessage(error.response?.data?.error || 'Failed to save settings');
      setTimeout(() => setErrorMessage(''), 5000);
    } finally {
      setSaving(false);
    }
  };

  const containerStyle: React.CSSProperties = {
    display: 'flex',
    minHeight: '100vh',
  };

  const contentStyle: React.CSSProperties = {
    flex: 1,
    padding: '24px 32px',
    backgroundColor: '#f5f6fa',
    marginLeft: 'var(--sidebar-width, 220px)',
    transition: 'margin-left 0.3s ease',
  };

  const cardStyle: React.CSSProperties = {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    marginBottom: '24px',
  };

  const sectionTitleStyle: React.CSSProperties = {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#1c4e80',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '2px solid #1c4e80',
  };

  const inputGroupStyle: React.CSSProperties = {
    marginBottom: '16px',
  };

  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '6px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
  };

  const inputStyle: React.CSSProperties = {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    fontSize: '14px',
    transition: 'border-color 0.2s',
  };

  const checkboxLabelStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    marginBottom: '12px',
  };

  const buttonStyle: React.CSSProperties = {
    backgroundColor: '#1c4e80',
    color: 'white',
    padding: '12px 24px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  };

  const logoPreviewStyle: React.CSSProperties = {
    width: '150px',
    height: '150px',
    objectFit: 'contain',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    padding: '8px',
    marginBottom: '8px',
  };

  if (loading) {
    return (
      <div style={containerStyle}>
        <Sidebar />
        <div style={{...contentStyle, display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
          <div>Loading...</div>
        </div>
      </div>
    );
  }

  return (
    <div style={containerStyle}>
      <Sidebar />
      <div style={contentStyle}>
        <div style={{ marginBottom: '32px' }}>
          <h1 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1c4e80', margin: 0 }}>Report Settings</h1>
          <p style={{ fontSize: '14px', color: '#6b7280', marginTop: '8px' }}>
            Customize the header and footer for PDF, Word, and Excel export reports
          </p>
        </div>

        {successMessage && (
          <div style={{...cardStyle, backgroundColor: '#d1fae5', border: '1px solid #10b981', color: '#065f46', padding: '12px 16px', marginBottom: '16px'}}>
            {successMessage}
          </div>
        )}

        {errorMessage && (
          <div style={{...cardStyle, backgroundColor: '#fee2e2', border: '1px solid #ef4444', color: '#991b1b', padding: '12px 16px', marginBottom: '16px'}}>
            {errorMessage}
          </div>
        )}

        {/* Header Settings */}
        <div style={cardStyle}>
          <h2 style={sectionTitleStyle}>Header Settings</h2>
          
          <div style={inputGroupStyle}>
            <label style={checkboxLabelStyle}>
              <input
                type="checkbox"
                checked={headerEnabled}
                onChange={(e) => setHeaderEnabled(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span>Enable Header</span>
            </label>
          </div>

          {headerEnabled && (
            <>
              <div style={inputGroupStyle}>
                <label style={labelStyle}>Layout Type</label>
                <select
                  value={headerLayoutType}
                  onChange={(e) => setHeaderLayoutType(e.target.value)}
                  style={inputStyle}
                >
                  <option value="three_column">Three Column (Logo, Text, Logo)</option>
                  <option value="two_column">Two Column (Logo, Text)</option>
                  <option value="single_column">Single Column (Text only)</option>
                </select>
              </div>

              {/* Logo Upload Section */}
              <div style={{ display: 'flex', gap: '32px', marginBottom: '24px' }}>
                {/* Left Logo */}
                <div style={{ flex: 1 }}>
                  <label style={checkboxLabelStyle}>
                    <input
                      type="checkbox"
                      checked={leftLogoEnabled}
                      onChange={(e) => setLeftLogoEnabled(e.target.checked)}
                      style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                    />
                    <span>Left Logo</span>
                  </label>
                  {leftLogoPreview && (
                    <img src={leftLogoPreview} alt="Left logo preview" style={logoPreviewStyle} />
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleLogoUpload(file, 'left');
                    }}
                    style={{ marginTop: '8px' }}
                  />
                </div>

                {/* Right Logo */}
                <div style={{ flex: 1 }}>
                  <label style={checkboxLabelStyle}>
                    <input
                      type="checkbox"
                      checked={rightLogoEnabled}
                      onChange={(e) => setRightLogoEnabled(e.target.checked)}
                      style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                    />
                    <span>Right Logo</span>
                  </label>
                  {rightLogoPreview && (
                    <img src={rightLogoPreview} alt="Right logo preview" style={logoPreviewStyle} />
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleLogoUpload(file, 'right');
                    }}
                    style={{ marginTop: '8px' }}
                  />
                </div>
              </div>

              {/* Header Text Fields */}
              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 1</label>
                <input
                  type="text"
                  value={headerLine1}
                  onChange={(e) => setHeaderLine1(e.target.value)}
                  style={inputStyle}
                  placeholder="Republic of the Philippines"
                />
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 2</label>
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
                  <input
                    type="text"
                    value={headerLine2}
                    onChange={(e) => setHeaderLine2(e.target.value)}
                    style={{...inputStyle, flex: 1}}
                    placeholder="CEBU TECHNOLOGICAL UNIVERSITY"
                  />
                  <input
                    type="color"
                    value={headerLine2Color}
                    onChange={(e) => setHeaderLine2Color(e.target.value)}
                    style={{ width: '60px', height: '40px', border: '1px solid #d1d5db', borderRadius: '8px', cursor: 'pointer' }}
                  />
                  <label style={checkboxLabelStyle}>
                    <input
                      type="checkbox"
                      checked={headerLine2Bold}
                      onChange={(e) => setHeaderLine2Bold(e.target.checked)}
                      style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                    />
                    <span>Bold</span>
                  </label>
                </div>
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 3</label>
                <input
                  type="text"
                  value={headerLine3}
                  onChange={(e) => setHeaderLine3(e.target.value)}
                  style={inputStyle}
                  placeholder="M. J. Cuenco Avenue Cor. R. Palma Street, Cebu City, Philippines"
                />
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 4</label>
                <input
                  type="text"
                  value={headerLine4}
                  onChange={(e) => setHeaderLine4(e.target.value)}
                  style={inputStyle}
                  placeholder="Website: http://www.ctu.edu.ph"
                />
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 5</label>
                <input
                  type="text"
                  value={headerLine5}
                  onChange={(e) => setHeaderLine5(e.target.value)}
                  style={inputStyle}
                  placeholder="Phone: +6332 402 4060 loc. 1146"
                />
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Header Line 6</label>
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
                  <input
                    type="text"
                    value={headerLine6}
                    onChange={(e) => setHeaderLine6(e.target.value)}
                    style={{...inputStyle, flex: 1}}
                    placeholder="UNIVERSITY ALUMNI AFFAIRS OFFICE"
                  />
                  <input
                    type="color"
                    value={headerLine6Color}
                    onChange={(e) => setHeaderLine6Color(e.target.value)}
                    style={{ width: '60px', height: '40px', border: '1px solid #d1d5db', borderRadius: '8px', cursor: 'pointer' }}
                  />
                  <label style={checkboxLabelStyle}>
                    <input
                      type="checkbox"
                      checked={headerLine6Bold}
                      onChange={(e) => setHeaderLine6Bold(e.target.checked)}
                      style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                    />
                    <span>Bold</span>
                  </label>
                </div>
              </div>
            </>
          )}
        </div>

        {/* Footer Settings */}
        <div style={cardStyle}>
          <h2 style={sectionTitleStyle}>Footer Settings</h2>
          
          <div style={inputGroupStyle}>
            <label style={checkboxLabelStyle}>
              <input
                type="checkbox"
                checked={footerEnabled}
                onChange={(e) => setFooterEnabled(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span>Enable Footer</span>
            </label>
          </div>

          {footerEnabled && (
            <>
              {/* Signature Section */}
              <div style={inputGroupStyle}>
                <label style={checkboxLabelStyle}>
                  <input
                    type="checkbox"
                    checked={signatureEnabled}
                    onChange={(e) => setSignatureEnabled(e.target.checked)}
                    style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                  />
                  <span>Enable Signature Section</span>
                </label>
              </div>

              {signatureEnabled && (
                <>
                  <div style={{display: 'flex', gap: '16px', marginTop: '16px'}}>
                    {/* Prepared By */}
                    <div style={{flex: 1, border: '1px solid #e5e7eb', borderRadius: '8px', padding: '16px', backgroundColor: '#f9fafb'}}>
                      <h3 style={{fontSize: '14px', fontWeight: 'bold', color: '#374151', marginBottom: '12px'}}>Prepared By</h3>
                      <div style={inputGroupStyle}>
                        <label style={labelStyle}>Name</label>
                        <input
                          type="text"
                          value={preparedByName}
                          onChange={(e) => setPreparedByName(e.target.value)}
                          style={inputStyle}
                          placeholder="MARIE JOY B. ALIT, Ph.D."
                        />
                      </div>
                      <div style={inputGroupStyle}>
                        <label style={labelStyle}>Title</label>
                        <input
                          type="text"
                          value={preparedByTitle}
                          onChange={(e) => setPreparedByTitle(e.target.value)}
                          style={inputStyle}
                          placeholder="University Director for Alumni Affairs"
                        />
                      </div>
                    </div>

                    {/* Approved By */}
                    <div style={{flex: 1, border: '1px solid #e5e7eb', borderRadius: '8px', padding: '16px', backgroundColor: '#f9fafb'}}>
                      <h3 style={{fontSize: '14px', fontWeight: 'bold', color: '#374151', marginBottom: '12px'}}>Approved By</h3>
                      <div style={inputGroupStyle}>
                        <label style={labelStyle}>Name</label>
                        <input
                          type="text"
                          value={approvedByName}
                          onChange={(e) => setApprovedByName(e.target.value)}
                          style={inputStyle}
                          placeholder="ROMEO P. MONTECILLO, Ph.D."
                        />
                      </div>
                      <div style={inputGroupStyle}>
                        <label style={labelStyle}>Title</label>
                        <input
                          type="text"
                          value={approvedByTitle}
                          onChange={(e) => setApprovedByTitle(e.target.value)}
                          style={inputStyle}
                          placeholder="Vice President for Student Affairs"
                        />
                      </div>
                    </div>
                  </div>
                  <div style={{borderTop: '1px solid #e5e7eb', marginTop: '24px', paddingTop: '24px'}}></div>
                </>
              )}

              <div style={inputGroupStyle}>
                <label style={checkboxLabelStyle}>
                  <input
                    type="checkbox"
                    checked={footerImageEnabled}
                    onChange={(e) => setFooterImageEnabled(e.target.checked)}
                    style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                  />
                  <span>Footer Image</span>
                </label>
              </div>

              {footerImageEnabled && (
                <div style={inputGroupStyle}>
                  {footerImagePreview && (
                    <img src={footerImagePreview} alt="Footer image preview" style={{...logoPreviewStyle, width: '100%', maxWidth: '400px', height: 'auto'}} />
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleLogoUpload(file, 'footer');
                    }}
                    style={{ marginTop: '8px' }}
                  />
                </div>
              )}

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Footer Text 1</label>
                <input
                  type="text"
                  value={footerText1}
                  onChange={(e) => setFooterText1(e.target.value)}
                  style={inputStyle}
                  placeholder="Generated by Cebu Technological University Alumni Affairs Office"
                />
              </div>

              <div style={inputGroupStyle}>
                <label style={labelStyle}>Footer Text 2</label>
                <input
                  type="text"
                  value={footerText2}
                  onChange={(e) => setFooterText2(e.target.value)}
                  style={inputStyle}
                  placeholder="This report is generated automatically by the Alumni Tracking System"
                />
              </div>
            </>
          )}
        </div>

        {/* Save Button */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
          <button
            onClick={handleSave}
            disabled={saving}
            style={{
              ...buttonStyle,
              backgroundColor: saving ? '#9ca3af' : '#1c4e80',
              cursor: saving ? 'not-allowed' : 'pointer',
            }}
          >
            {saving ? 'Saving...' : 'Save Settings'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReportSettingsPage;
